# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "umbrela"
version = "0.0.7"
description = "A Package for generating query-passage relevance assessment labels."
readme = "README.md"
authors = [
    { name = "Shivani Upadhyay", email = "sjupadhyay@uwaterloo.ca" },
    { name = "Ronak Pradeep", email = "rpradeep@uwaterloo.ca" },
    { name = "Jimmy Lin", email = "jimmylin@uwaterloo.ca" },
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["LLM", "evaluation", "information retrieval"]
dynamic = ["dependencies"]
requires-python = ">= 3.9"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.package-data]
umbrela = ["prompts/*.txt"]

[project.urls]
Homepage = "https://github.com/castorini/umbrela"

[tool.bumpver]
current_version = "0.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false


[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"', 'version = "{version}"'
]
"README.md" = [
    "{version}",
]

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "umbrela",
    "umbrela.utils",
    "prompts"
]
namespaces = false
